[package]
name = "ad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ad"
crate-type = ["cdylib"]

[dependencies]
inquire = "0.7.5"
pyo3 = "0.21.1"
rustyline = "14.0.0"
