[package]
name = "dns_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
list_comprehension_macro = "0.1.1"
maplit = "1.0.2"
net-literals = "0.2.0"
no-panic = "0.1.29"
