[package]
name = "lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.10"
pest_consume = "1.1.3"
pest_derive = "2.7.10"
thiserror = "1.0.59"
try_map = "0.3.1"
